\hypertarget{classX86ISA_1_1DebugException}{
\section{クラス DebugException}
\label{classX86ISA_1_1DebugException}\index{X86ISA::DebugException@{X86ISA::DebugException}}
}


{\ttfamily \#include $<$faults.hh$>$}DebugExceptionに対する継承グラフ:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=4cm]{classX86ISA_1_1DebugException}
\end{center}
\end{figure}
\subsection*{Public メソッド}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classX86ISA_1_1DebugException_ae01398f1b85aec8dfec381bb355fa30a}{DebugException} ()
\end{DoxyCompactItemize}


\subsection{コンストラクタとデストラクタ}
\hypertarget{classX86ISA_1_1DebugException_ae01398f1b85aec8dfec381bb355fa30a}{
\index{X86ISA::DebugException@{X86ISA::DebugException}!DebugException@{DebugException}}
\index{DebugException@{DebugException}!X86ISA::DebugException@{X86ISA::DebugException}}
\subsubsection[{DebugException}]{\setlength{\rightskip}{0pt plus 5cm}{\bf DebugException} ()\hspace{0.3cm}{\ttfamily  \mbox{[}inline\mbox{]}}}}
\label{classX86ISA_1_1DebugException_ae01398f1b85aec8dfec381bb355fa30a}



\begin{DoxyCode}
207                          :
208             X86FaultBase("Debug", "#DB", 1)
209         {}
    };
\end{DoxyCode}


このクラスの説明は次のファイルから生成されました:\begin{DoxyCompactItemize}
\item 
arch/x86/\hyperlink{arch_2x86_2faults_8hh}{faults.hh}\end{DoxyCompactItemize}
